# Generated by Django 2.0.5 on 2018-05-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0002_project_cost_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectuserdata',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is the user active'),
        ),
        migrations.AlterField(
            model_name='projectuserdata',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is an administrator'),
        ),
        migrations.AlterField(
            model_name='projectuserdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users_data', to='GamePlanner.Project'),
        ),
    ]
