# Generated by Django 2.0.5 on 2018-05-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0005_auto_20180516_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='surname',
        ),
    ]
