# Generated by Django 2.0.5 on 2018-05-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0008_auto_20180516_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_cost',
            field=models.FloatField(verbose_name='Estimated time cost'),
        ),
        migrations.AlterField(
            model_name='task',
            name='final_cost',
            field=models.FloatField(verbose_name='Final cost'),
        ),
    ]
