# Generated by Django 2.0.5 on 2018-05-16 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0009_auto_20180516_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='GamePlanner.Project'),
        ),
        migrations.AddField(
            model_name='platform',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='GamePlanner.Project'),
        ),
        migrations.AlterField(
            model_name='category',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='GamePlanner.Project'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='GamePlanner.Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='design_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_elements', to='GamePlanner.DesignElement'),
        ),
    ]
