# Generated by Django 2.0.5 on 2018-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0010_auto_20180516_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing Date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='starting_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Starting Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Task Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
