# Generated by Django 2.0.5 on 2018-05-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0011_auto_20180517_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platform',
            old_name='platform',
            new_name='project',
        ),
    ]
