# Generated by Django 2.0.5 on 2018-05-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0012_auto_20180517_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='final_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Final cost'),
        ),
        migrations.AlterField(
            model_name='task',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last update date'),
        ),
    ]
