# Generated by Django 2.0.5 on 2018-05-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0014_auto_20180517_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='cost_metric',
            field=models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('POINTS', 'Points')], default='HOURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=200),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
