# Generated by Django 2.0.5 on 2018-05-18 20:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0016_auto_20180518_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=markdownx.models.MarkdownxField(verbose_name='Task Description'),
        ),
    ]
