# Generated by Django 2.0.5 on 2018-05-19 10:50

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0018_designelement_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='designelement',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='description'),
        ),
    ]
