# Generated by Django 2.0.5 on 2018-05-26 08:45

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0020_auto_20180519_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='designelement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='design_elements', to='GamePlanner.Project'),
        ),
        migrations.AlterField(
            model_name='designelement',
            name='description',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True, verbose_name='Element description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='design_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='GamePlanner.DesignElement'),
        ),
    ]
