# Generated by Django 2.0.5 on 2018-05-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0022_auto_20180529_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='GamePlanner.SubCategory'),
            preserve_default=False,
        ),
    ]
