# Generated by Django 2.0.5 on 2018-05-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0023_task_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_types', to='GamePlanner.Project')),
            ],
        ),
    ]
