# Generated by Django 2.0.5 on 2018-05-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0024_elementtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='designelement',
            name='element_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='GamePlanner.ElementType'),
            preserve_default=False,
        ),
    ]
