# Generated by Django 2.0.5 on 2018-06-22 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0025_designelement_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuserdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
