# Generated by Django 2.0.5 on 2018-06-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePlanner', '0027_task_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='stage',
            new_name='status',
        ),
    ]
